# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forcestamp_ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from pyqtgraph import GraphicsLayoutWidget


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        windowWidth = 1360
        windowHeight = 545
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(windowWidth, windowHeight)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setMinimumHeight(windowHeight)
        MainWindow.setMinimumWidth(windowWidth)
        MainWindow.setMaximumHeight(windowHeight)
        MainWindow.setMaximumWidth(windowWidth)

        spinboxWidth = 70
        spinboxHeight = 26
        # MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        # self.graphicsView = GraphicsLayoutWidget(self.centralwidget)
        # self.graphicsView = GraphicsView(self.centralwidget)
        self.graphicsView = GraphicsLayoutWidget(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(10, 10, 925, 525))
        self.graphicsView.setObjectName("graphicsView")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(1150, 30, 80, 35))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1260, 30, 70, 35))
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setText("Start")
        self.GroupParameterScale = QtWidgets.QGroupBox(self.centralwidget)
        self.GroupParameterScale.setGeometry(QtCore.QRect(945, 90, 406, 446))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.GroupParameterScale.setFont(font)
        self.GroupParameterScale.setAlignment(QtCore.Qt.AlignCenter)
        self.GroupParameterScale.setFlat(False)
        self.GroupParameterScale.setCheckable(False)
        self.GroupParameterScale.setObjectName("GroupParameterScale")
        self.progressBar_posx = QtWidgets.QProgressBar(self.GroupParameterScale)
        self.progressBar_posx.setGeometry(QtCore.QRect(20, 80, 40, 260))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.progressBar_posx.setFont(font)
        self.progressBar_posx.setProperty("value", 0)
        self.progressBar_posx.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar_posx.setTextVisible(True)
        self.progressBar_posx.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_posx.setInvertedAppearance(False)
        self.progressBar_posx.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_posx.setObjectName("progressBar_posx")
        self.label_posx = QtWidgets.QLabel(self.GroupParameterScale)
        self.label_posx.setGeometry(QtCore.QRect(10, 380, 60, 20))
        self.label_posx.setAlignment(QtCore.Qt.AlignCenter)
        self.label_posx.setObjectName("label_posx")
        self.label_posy = QtWidgets.QLabel(self.GroupParameterScale)
        self.label_posy.setGeometry(QtCore.QRect(90, 380, 60, 20))
        self.label_posy.setAlignment(QtCore.Qt.AlignCenter)
        self.label_posy.setObjectName("label_posy")
        self.progressBar_posy = QtWidgets.QProgressBar(self.GroupParameterScale)
        self.progressBar_posy.setGeometry(QtCore.QRect(100, 80, 40, 260))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.progressBar_posy.setFont(font)
        self.progressBar_posy.setProperty("value", 0)
        self.progressBar_posy.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar_posy.setTextVisible(True)
        self.progressBar_posy.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_posy.setInvertedAppearance(False)
        self.progressBar_posy.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_posy.setObjectName("progressBar_posy")
        self.label_force = QtWidgets.QLabel(self.GroupParameterScale)
        self.label_force.setGeometry(QtCore.QRect(170, 380, 60, 20))
        self.label_force.setAlignment(QtCore.Qt.AlignCenter)
        self.label_force.setObjectName("label_force")
        self.progressBar_force = QtWidgets.QProgressBar(self.GroupParameterScale)
        self.progressBar_force.setGeometry(QtCore.QRect(180, 80, 40, 260))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.progressBar_force.setFont(font)
        self.progressBar_force.setProperty("value", 0)
        self.progressBar_force.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar_force.setTextVisible(True)
        self.progressBar_force.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_force.setInvertedAppearance(False)
        self.progressBar_force.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_force.setObjectName("progressBar_force")
        self.label_cof_x = QtWidgets.QLabel(self.GroupParameterScale)
        self.label_cof_x.setGeometry(QtCore.QRect(250, 380, 60, 20))
        self.label_cof_x.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cof_x.setObjectName("label_cof_x")
        self.progressBar_cof_x = QtWidgets.QProgressBar(self.GroupParameterScale)
        self.progressBar_cof_x.setGeometry(QtCore.QRect(260, 80, 40, 260))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.progressBar_cof_x.setFont(font)
        self.progressBar_cof_x.setProperty("value", 0)
        self.progressBar_cof_x.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar_cof_x.setTextVisible(True)
        self.progressBar_cof_x.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_cof_x.setInvertedAppearance(False)
        self.progressBar_cof_x.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_cof_x.setObjectName("progressBar_cof_x")
        self.label_cof_y = QtWidgets.QLabel(self.GroupParameterScale)
        self.label_cof_y.setGeometry(QtCore.QRect(330, 380, 60, 20))
        self.label_cof_y.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cof_y.setObjectName("label_cof_y")
        self.progressBar_cof_y = QtWidgets.QProgressBar(self.GroupParameterScale)
        self.progressBar_cof_y.setGeometry(QtCore.QRect(340, 80, 40, 260))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.progressBar_cof_y.setFont(font)
        self.progressBar_cof_y.setProperty("value", 0)
        self.progressBar_cof_y.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar_cof_y.setTextVisible(True)
        self.progressBar_cof_y.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_cof_y.setInvertedAppearance(False)
        self.progressBar_cof_y.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_cof_y.setObjectName("progressBar_cof_y")
        font = QtGui.QFont()
        font.setPointSize(8)
        self.value_posx = QtWidgets.QLabel(self.GroupParameterScale)
        self.value_posx.setGeometry(QtCore.QRect(10, 405, 60, 20))
        self.value_posx.setAlignment(QtCore.Qt.AlignCenter)
        self.value_posx.setObjectName("value_posx")
        self.value_posy = QtWidgets.QLabel(self.GroupParameterScale)
        self.value_posy.setGeometry(QtCore.QRect(90, 405, 60, 20))
        self.value_posy.setAlignment(QtCore.Qt.AlignCenter)
        self.value_posy.setObjectName("value_posy")
        self.value_force = QtWidgets.QLabel(self.GroupParameterScale)
        self.value_force.setGeometry(QtCore.QRect(170, 405, 60, 20))
        self.value_force.setAlignment(QtCore.Qt.AlignCenter)
        self.value_force.setObjectName("value_force")
        self.value_cof_x = QtWidgets.QLabel(self.GroupParameterScale)
        self.value_cof_x.setGeometry(QtCore.QRect(250, 405, 60, 20))
        self.value_cof_x.setAlignment(QtCore.Qt.AlignCenter)
        self.value_cof_x.setObjectName("value_vex")
        self.value_cof_y = QtWidgets.QLabel(self.GroupParameterScale)
        self.value_cof_y.setGeometry(QtCore.QRect(330, 405, 60, 20))
        self.value_cof_y.setAlignment(QtCore.Qt.AlignCenter)
        self.value_cof_y.setObjectName("value_cof_y")

        font = QtGui.QFont()
        font.setPointSize(16)

        self.doubleSpinBox_posx_max = QtWidgets.QDoubleSpinBox(self.GroupParameterScale)
        self.doubleSpinBox_posx_max.setGeometry(QtCore.QRect(10, 40, spinboxWidth, spinboxHeight))
        self.doubleSpinBox_posx_max.setObjectName("doubleSpinBox_posx_max")
        self.doubleSpinBox_posx_min = QtWidgets.QDoubleSpinBox(self.GroupParameterScale)
        self.doubleSpinBox_posx_min.setGeometry(QtCore.QRect(10, 350, spinboxWidth, spinboxHeight))
        self.doubleSpinBox_posx_min.setObjectName("doubleSpinBox_posx_min")
        self.doubleSpinBox_posy_min = QtWidgets.QDoubleSpinBox(self.GroupParameterScale)
        self.doubleSpinBox_posy_min.setGeometry(QtCore.QRect(90, 350, spinboxWidth, spinboxHeight))
        self.doubleSpinBox_posy_min.setObjectName("doubleSpinBox_posy_min")
        self.doubleSpinBox_posy_max = QtWidgets.QDoubleSpinBox(self.GroupParameterScale)
        self.doubleSpinBox_posy_max.setGeometry(QtCore.QRect(90, 40, spinboxWidth, spinboxHeight))
        self.doubleSpinBox_posy_max.setObjectName("doubleSpinBox_posy_max")
        self.doubleSpinBox_force_max = QtWidgets.QDoubleSpinBox(self.GroupParameterScale)
        self.doubleSpinBox_force_max.setGeometry(QtCore.QRect(170, 40, spinboxWidth, spinboxHeight))
        self.doubleSpinBox_force_max.setObjectName("doubleSpinBox_force_max")
        self.doubleSpinBox_force_min = QtWidgets.QDoubleSpinBox(self.GroupParameterScale)
        self.doubleSpinBox_force_min.setGeometry(QtCore.QRect(170, 350, spinboxWidth, spinboxHeight))
        self.doubleSpinBox_force_min.setObjectName("doubleSpinBox_force_min")
        self.doubleSpinBox_cof_x_max = QtWidgets.QDoubleSpinBox(self.GroupParameterScale)
        self.doubleSpinBox_cof_x_max.setGeometry(QtCore.QRect(250, 40, spinboxWidth, spinboxHeight))
        self.doubleSpinBox_cof_x_max.setObjectName("doubleSpinBox_cof_x_max")
        self.doubleSpinBox_cof_x_min = QtWidgets.QDoubleSpinBox(self.GroupParameterScale)
        self.doubleSpinBox_cof_x_min.setGeometry(QtCore.QRect(250, 350, spinboxWidth, spinboxHeight))
        self.doubleSpinBox_cof_x_min.setObjectName("doubleSpinBox_cof_x_min")
        self.doubleSpinBox_cof_y_max = QtWidgets.QDoubleSpinBox(self.GroupParameterScale)
        self.doubleSpinBox_cof_y_max.setGeometry(QtCore.QRect(330, 40, spinboxWidth, spinboxHeight))
        self.doubleSpinBox_cof_y_max.setObjectName("doubleSpinBox_cof_y_max")
        self.doubleSpinBox_cof_y_min = QtWidgets.QDoubleSpinBox(self.GroupParameterScale)
        self.doubleSpinBox_cof_y_min.setGeometry(QtCore.QRect(330, 350, spinboxWidth, spinboxHeight))
        self.doubleSpinBox_cof_y_min.setObjectName("doubleSpinBox_cof_y_min")

        self.doubleSpinBox_force_sens = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_force_sens.setGeometry(QtCore.QRect(1050, 25, spinboxWidth, spinboxHeight))
        self.doubleSpinBox_force_sens.setObjectName("doubleSpinBox_force_sense")
        self.doubleSpinBox_cof_sens = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_cof_sens.setGeometry(QtCore.QRect(1050, 55, spinboxWidth, spinboxHeight))
        self.doubleSpinBox_cof_sens.setObjectName("doubleSpinBox_cof_sense")

        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_force_sens = QtWidgets.QLabel(self.centralwidget)
        self.label_force_sens.setGeometry(QtCore.QRect(950, 15, 100, 40))
        self.label_force_sens.setFont(font)
        self.label_force_sens.setObjectName("label_force_sens")
        self.label_cof_sens = QtWidgets.QLabel(self.centralwidget)
        self.label_cof_sens.setGeometry(QtCore.QRect(950, 45, 100, 40))
        self.label_cof_sens.setFont(font)
        self.label_cof_sens.setObjectName("label_cof_sens")

        # MainWindow.setCentralWidget(self.centralwidget)
        # self.statusbar = QtWidgets.QStatusBar(MainWindow)
        # self.statusbar.setObjectName("statusbar")
        # MainWindow.setStatusBar(self.statusbar)
        MainWindow.setTabOrder(self.doubleSpinBox_posx_max, self.doubleSpinBox_posx_min)
        MainWindow.setTabOrder(self.doubleSpinBox_posx_min, self.doubleSpinBox_posy_max)
        MainWindow.setTabOrder(self.doubleSpinBox_posy_max, self.doubleSpinBox_posy_min)
        MainWindow.setTabOrder(self.doubleSpinBox_posy_min, self.doubleSpinBox_force_max)
        MainWindow.setTabOrder(self.doubleSpinBox_force_max, self.doubleSpinBox_force_min)
        MainWindow.setTabOrder(self.doubleSpinBox_force_min, self.doubleSpinBox_cof_x_max)
        MainWindow.setTabOrder(self.doubleSpinBox_cof_x_max, self.doubleSpinBox_cof_x_min)
        MainWindow.setTabOrder(self.doubleSpinBox_cof_x_min, self.doubleSpinBox_cof_y_max)
        MainWindow.setTabOrder(self.doubleSpinBox_cof_y_max, self.doubleSpinBox_cof_y_min)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ForceStamps"))
        self.GroupParameterScale.setTitle(_translate("MainWindow", "Parameter Scale"))
        self.label_posx.setText(_translate("MainWindow", "pos_x"))
        self.label_posy.setText(_translate("MainWindow", "pos_y"))
        self.label_force.setText(_translate("MainWindow", "force"))
        self.label_cof_x.setText(_translate("MainWindow", "cof_x"))
        self.label_cof_y.setText(_translate("MainWindow", "cof_y"))
        self.label_force_sens.setText(_translate("MainWindow", "Force sens."))
        self.label_cof_sens.setText(_translate("MainWindow", "CoF sens."))
        self.value_posx.setText(_translate("MainWindow", "0.0"))
        self.value_posy.setText(_translate("MainWindow", "0.0"))
        self.value_force.setText(_translate("MainWindow", "0.0"))
        self.value_cof_x.setText(_translate("MainWindow", "0.0"))
        self.value_cof_y.setText(_translate("MainWindow", "0.0"))
        self.progressBar_posx.setFormat(_translate("MainWindow", "%.02f"))
        self.progressBar_posy.setFormat(_translate("MainWindow", "%.02f"))
        self.progressBar_force.setFormat(_translate("MainWindow", "%.02f"))
        self.progressBar_cof_x.setFormat(_translate("MainWindow", "%.02f"))
        self.progressBar_cof_y.setFormat(_translate("MainWindow", "%.02f"))
