# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forcestamp_ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from pyqtgraph import GraphicsLayoutWidget


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        windowWidth = 1360
        windowHeight = 545
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(windowWidth, windowHeight)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setMinimumHeight(windowHeight)
        MainWindow.setMinimumWidth(windowWidth)
        MainWindow.setMaximumHeight(windowHeight)
        MainWindow.setMaximumWidth(windowWidth)

        spinboxWidth = 70
        spinboxHeight = 26
        # MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        # self.graphicsView = GraphicsLayoutWidget(self.centralwidget)
        # self.graphicsView = GraphicsView(self.centralwidget)
        self.graphicsView = GraphicsLayoutWidget(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(10, 10, 925, 525))
        self.graphicsView.setObjectName("graphicsView")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(1160, 30, 80, 35))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.GroupParameterScale = QtWidgets.QGroupBox(self.centralwidget)
        self.GroupParameterScale.setGeometry(QtCore.QRect(945, 90, 406, 446))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.GroupParameterScale.setFont(font)
        self.GroupParameterScale.setAlignment(QtCore.Qt.AlignCenter)
        self.GroupParameterScale.setFlat(False)
        self.GroupParameterScale.setCheckable(False)
        self.GroupParameterScale.setObjectName("GroupParameterScale")
        self.progressBar_posx = QtWidgets.QProgressBar(self.GroupParameterScale)
        self.progressBar_posx.setGeometry(QtCore.QRect(20, 90, 40, 260))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.progressBar_posx.setFont(font)
        self.progressBar_posx.setProperty("value", 0)
        self.progressBar_posx.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar_posx.setTextVisible(True)
        self.progressBar_posx.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_posx.setInvertedAppearance(False)
        self.progressBar_posx.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_posx.setObjectName("progressBar_posx")
        self.label_posx = QtWidgets.QLabel(self.GroupParameterScale)
        self.label_posx.setGeometry(QtCore.QRect(10, 400, 60, 20))
        self.label_posx.setAlignment(QtCore.Qt.AlignCenter)
        self.label_posx.setObjectName("label_posx")
        self.label_posy = QtWidgets.QLabel(self.GroupParameterScale)
        self.label_posy.setGeometry(QtCore.QRect(90, 400, 60, 20))
        self.label_posy.setAlignment(QtCore.Qt.AlignCenter)
        self.label_posy.setObjectName("label_posy")
        self.progressBar_posy = QtWidgets.QProgressBar(self.GroupParameterScale)
        self.progressBar_posy.setGeometry(QtCore.QRect(100, 90, 40, 260))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.progressBar_posy.setFont(font)
        self.progressBar_posy.setProperty("value", 0)
        self.progressBar_posy.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar_posy.setTextVisible(True)
        self.progressBar_posy.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_posy.setInvertedAppearance(False)
        self.progressBar_posy.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_posy.setObjectName("progressBar_posy")
        self.label_force = QtWidgets.QLabel(self.GroupParameterScale)
        self.label_force.setGeometry(QtCore.QRect(170, 400, 60, 20))
        self.label_force.setAlignment(QtCore.Qt.AlignCenter)
        self.label_force.setObjectName("label_force")
        self.progressBar_force = QtWidgets.QProgressBar(self.GroupParameterScale)
        self.progressBar_force.setGeometry(QtCore.QRect(180, 90, 40, 260))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.progressBar_force.setFont(font)
        self.progressBar_force.setProperty("value", 0)
        self.progressBar_force.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar_force.setTextVisible(True)
        self.progressBar_force.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_force.setInvertedAppearance(False)
        self.progressBar_force.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_force.setObjectName("progressBar_force")
        self.label_vecx = QtWidgets.QLabel(self.GroupParameterScale)
        self.label_vecx.setGeometry(QtCore.QRect(250, 400, 60, 20))
        self.label_vecx.setAlignment(QtCore.Qt.AlignCenter)
        self.label_vecx.setObjectName("label_vecx")
        self.progressBar_vecx = QtWidgets.QProgressBar(self.GroupParameterScale)
        self.progressBar_vecx.setGeometry(QtCore.QRect(260, 90, 40, 260))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.progressBar_vecx.setFont(font)
        self.progressBar_vecx.setProperty("value", 0)
        self.progressBar_vecx.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar_vecx.setTextVisible(True)
        self.progressBar_vecx.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_vecx.setInvertedAppearance(False)
        self.progressBar_vecx.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_vecx.setObjectName("progressBar_vecx")
        self.label_vecy = QtWidgets.QLabel(self.GroupParameterScale)
        self.label_vecy.setGeometry(QtCore.QRect(330, 400, 60, 20))
        self.label_vecy.setAlignment(QtCore.Qt.AlignCenter)
        self.label_vecy.setObjectName("label_vecy")
        self.progressBar_vecy = QtWidgets.QProgressBar(self.GroupParameterScale)
        self.progressBar_vecy.setGeometry(QtCore.QRect(340, 90, 40, 260))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.progressBar_vecy.setFont(font)
        self.progressBar_vecy.setProperty("value", 0)
        self.progressBar_vecy.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar_vecy.setTextVisible(True)
        self.progressBar_vecy.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_vecy.setInvertedAppearance(False)
        self.progressBar_vecy.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_vecy.setObjectName("progressBar_vecy")

        font = QtGui.QFont()
        font.setPointSize(16)

        self.doubleSpinBox_posx_max = QtWidgets.QDoubleSpinBox(self.GroupParameterScale)
        self.doubleSpinBox_posx_max.setGeometry(QtCore.QRect(10, 50, spinboxWidth, spinboxHeight))
        self.doubleSpinBox_posx_max.setObjectName("doubleSpinBox_posx_max")
        self.doubleSpinBox_posx_min = QtWidgets.QDoubleSpinBox(self.GroupParameterScale)
        self.doubleSpinBox_posx_min.setGeometry(QtCore.QRect(10, 360, spinboxWidth, spinboxHeight))
        self.doubleSpinBox_posx_min.setObjectName("doubleSpinBox_posx_min")
        self.doubleSpinBox_posy_min = QtWidgets.QDoubleSpinBox(self.GroupParameterScale)
        self.doubleSpinBox_posy_min.setGeometry(QtCore.QRect(90, 360, spinboxWidth, spinboxHeight))
        self.doubleSpinBox_posy_min.setObjectName("doubleSpinBox_posy_min")
        self.doubleSpinBox_posy_max = QtWidgets.QDoubleSpinBox(self.GroupParameterScale)
        self.doubleSpinBox_posy_max.setGeometry(QtCore.QRect(90, 50, spinboxWidth, spinboxHeight))
        self.doubleSpinBox_posy_max.setObjectName("doubleSpinBox_posy_max")
        self.doubleSpinBox_force_max = QtWidgets.QDoubleSpinBox(self.GroupParameterScale)
        self.doubleSpinBox_force_max.setGeometry(QtCore.QRect(170, 50, spinboxWidth, spinboxHeight))
        self.doubleSpinBox_force_max.setObjectName("doubleSpinBox_force_max")
        self.doubleSpinBox_force_min = QtWidgets.QDoubleSpinBox(self.GroupParameterScale)
        self.doubleSpinBox_force_min.setGeometry(QtCore.QRect(170, 360, spinboxWidth, spinboxHeight))
        self.doubleSpinBox_force_min.setObjectName("doubleSpinBox_force_min")
        self.doubleSpinBox_vecx_max = QtWidgets.QDoubleSpinBox(self.GroupParameterScale)
        self.doubleSpinBox_vecx_max.setGeometry(QtCore.QRect(250, 50, spinboxWidth, spinboxHeight))
        self.doubleSpinBox_vecx_max.setObjectName("doubleSpinBox_vecx_max")
        self.doubleSpinBox_vecx_min = QtWidgets.QDoubleSpinBox(self.GroupParameterScale)
        self.doubleSpinBox_vecx_min.setGeometry(QtCore.QRect(250, 360, spinboxWidth, spinboxHeight))
        self.doubleSpinBox_vecx_min.setObjectName("doubleSpinBox_vecx_min")
        self.doubleSpinBox_vecy_max = QtWidgets.QDoubleSpinBox(self.GroupParameterScale)
        self.doubleSpinBox_vecy_max.setGeometry(QtCore.QRect(330, 50, spinboxWidth, spinboxHeight))
        self.doubleSpinBox_vecy_max.setObjectName("doubleSpinBox_vecy_max")
        self.doubleSpinBox_vecy_min = QtWidgets.QDoubleSpinBox(self.GroupParameterScale)
        self.doubleSpinBox_vecy_min.setGeometry(QtCore.QRect(330, 360, spinboxWidth, spinboxHeight))
        self.doubleSpinBox_vecy_min.setObjectName("doubleSpinBox_vecy_min")

        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_ID = QtWidgets.QLabel(self.centralwidget)
        self.label_ID.setGeometry(QtCore.QRect(1050, 27, 100, 40))
        self.label_ID.setFont(font)
        self.label_ID.setObjectName("label_ID")
        # MainWindow.setCentralWidget(self.centralwidget)
        # self.statusbar = QtWidgets.QStatusBar(MainWindow)
        # self.statusbar.setObjectName("statusbar")
        # MainWindow.setStatusBar(self.statusbar)
        MainWindow.setTabOrder(self.doubleSpinBox_posx_max, self.doubleSpinBox_posx_min)
        MainWindow.setTabOrder(self.doubleSpinBox_posx_min, self.doubleSpinBox_posy_max)
        MainWindow.setTabOrder(self.doubleSpinBox_posy_max, self.doubleSpinBox_posy_min)
        MainWindow.setTabOrder(self.doubleSpinBox_posy_min, self.doubleSpinBox_force_max)
        MainWindow.setTabOrder(self.doubleSpinBox_force_max, self.doubleSpinBox_force_min)
        MainWindow.setTabOrder(self.doubleSpinBox_force_min, self.doubleSpinBox_vecx_max)
        MainWindow.setTabOrder(self.doubleSpinBox_vecx_max, self.doubleSpinBox_vecx_min)
        MainWindow.setTabOrder(self.doubleSpinBox_vecx_min, self.doubleSpinBox_vecy_max)
        MainWindow.setTabOrder(self.doubleSpinBox_vecy_max, self.doubleSpinBox_vecy_min)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ForceStamp"))
        self.GroupParameterScale.setTitle(_translate("MainWindow", "Parameter Scale"))
        self.label_posx.setText(_translate("MainWindow", "PosX"))
        self.label_posy.setText(_translate("MainWindow", "PosY"))
        self.label_force.setText(_translate("MainWindow", "Force"))
        self.label_vecx.setText(_translate("MainWindow", "VecX"))
        self.label_vecy.setText(_translate("MainWindow", "VecY"))
        self.label_ID.setText(_translate("MainWindow", "Marker ID"))
        self.progressBar_posx.setFormat(_translate("MainWindow", "%.02f"))
        self.progressBar_posy.setFormat(_translate("MainWindow", "%.02f"))
        self.progressBar_force.setFormat(_translate("MainWindow", "%.02f"))
        self.progressBar_vecx.setFormat(_translate("MainWindow", "%.02f"))
        self.progressBar_vecy.setFormat(_translate("MainWindow", "%.02f"))
